# Generated by Django 4.0.3 on 2022-03-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardapp', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
